language: java
jdk:
- openjdk8
dist: bionic
notifications:
  email:
    recipients:
    - dev@dattack.com
    on_success: always
    on_failure: always
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: WAQ/FcdxbRT9UqJQxNCLtSfqpbzKtDbkaIMaZAdf/hFryQCrctF20mOFNPuuzJC8cqJgNzw6Hsj3pG/Pl6m0DEbR4NgSKDkhIWdjbgL+NcMYuYjtVst6k5x3tDfYiLBSSDah4g6C2g4pHLSkNrSAYP3dBsr0niU275S4hiAayzCvmyxbRd3rAuByzZ/cnD324PZzEyUyQi7/rtoxHFnUkNmyIQyLsiDebGw9aCzJ3LaSNCgex/XlMrWWxWfwl/1QCu4aJMKX1TuJv3syLPHkRGUA3ti1aPqup5eq4FfmBTbxIKDNeRoYzfilFUmMeLmv6OvF1/5kqQwNT989R9ga1KVWf60uP2+ZWXngIDfBu0Ph3U2V9LdGtd3fsegzimsnORZ9Qz9JDXBVyKlBwJ4xAsBp4c/tJXzXRepqcfmE8urDKB3POAxxYnk8hCgO0i3bA/pVPaGf/1agafv7OBE6tusN/w63Hk7FYhp2abuG8Ekdas1hKXHUYiyWm2X28jPT5iCP2vkD2JTsNeeP4azbHiv6oD4LDxMWyp+waVwZPNhNy4tdQpm5nW/H49serGXFLi9VOfOd/o/iJGz2IG5xZ409lh7ZFWk5uWh46I61nCFmqvRhD4sAz7KfZ8dd2iMkvXhiRTkwuLGcsIKrotHP6FoFMZ1iDOGW9MYf0t+WX1w=
  - secure: h3efZVSYnIv6ExWz70tbs/2HtBhB7YX5UJ++/EgD4BjEVKExgGijh89LbFAUH5vCQIdNCHNfduArvFIFRKJgW5oGjfcp3CEgjHhDf6Cnhq3uK+cCVhWpBeQWNCaFHk4yRNpmPMcRdVtR+c7qEH3QNvyFBkphXWAp6ZSz4svSLZ+q9JfyWLB5tOUfH/srvu8TReLYfLOG8h8X22eVfwkWk/A1eaihFv9T05ldlpF39lqWsXKXKCyezvHQ2EsuxTtKI88v0FXECliv2vqUGRx8qXspd+u0bPVxmyvHVcGWeSLpdO1OEyvpw80BSKEDRm5jfZ8Xo//LwmRT8FaM7wkfbzC6sk4Zv7Uig6oL/WYEzTyMpXU4+TWHEofDuOxn4Bo+toCWZgiLTSseaym9v6+KNGi33hO1WP9Vu2enUMf4vDeeDs0c0TA4FA/yKv1f8ThQQ6jTWfSQHnGy8Z2pRlSchAbFvDzNUsw8XfpzZT+bNNEuqnrQVwEC47tLHtg83mxvM8auo21Jo3HpU+GgYw5a1N132I8mf9KcRDDdv4zYSGOeCmIsUNa2ECaWY6VXhE6kcReamtnOPhJmizCD4V782y7v0eOMeTufdNiloNM3j3P5ecf8CbHSqTtnZmEn7DP40AWo6RPd/wxfLWi/4XD1eYm6Mslc7Kt4pw38DsGmB8Q=
  - secure: iEhPb0VJ7XAqmsBsfc4NNZAh9tb33EIusmanitqDMBwKTTrzkeOrwAK2KiiZqU2K4ecxljoiv/L4Ho7uCxe5ujQcJ0tHNXgG1WJXNhDD59IIxcbOuMnKzW+GIwGwC9hagJd4pepdFdH5wnxKTdOd+qb1MysE/hLiyILRy90ObdLk6w9PZ5eec0g6qz/a3zZYCna+hbVp07UuXpVq6C4FdDOPUSjwoBtGShvAR6SBYAzG3kImEQoDfbIgL9yp1ieFAfYh1VtoYKqXQGnb+5oNsI7L5avSEORPDXn+/SgH+cYmWX2E+Omw+hZSKR3Srxv3low5pQ1x+7ctTNy6euPqt1xrZQrlcUoy0f3XGceeFYWEjfdBQ2xsu27/s1gVWwjjSVJPT17dzPTSQSlC4hXgpMW44iYcublTRoIBjK9JUTvIlHK/HQJF3t150vtDP9Kj5sLP2Onej1WLsDcUw9Cl1Xqb2nAFl0aWlvThhVQYut6vyMKQa7kRlmE4sQZyhX3178RRRaOk4/UgsK2K4yWr4pkwfno814tP10qsqGAZG9COw30QZSjDoSbNqXJU0JtJszDZUh9LegThkGv9hLFx03KceyDwhQG5kBHzKIlJX6Ejt3WXNHXqpaoH6jwr6EbbnIz3CdLBePBxqmkKekmwoSYkOSUfC3xD9QIlePxHftA=
  - secure: FmrcKO+uOxfECAYqjoh1QBehg5MnEdHUXHHc3uU9iqR+FOj5JfP1zmy9bsVWRYWD1+/zZUtdfWTcIsnky/LYVVWjGfzVHisAay6zF/fKIZOXck1MY51uP09Ldo2bsXj7o1cdrIf//OxKRjGSLBIZwmRMGcj/OQWPRc10RGadpJbniJwWXHfe3EK03V0fjnFfowNFf7HFZcPu6rIOoeseGfzLik3DUHLEt6MwaQrJ1QDxDeomO0ErQzyQtnPcn86WWEl+l0hvOKDW65BqM9EDbH6JsNmWxTlmk4ZQpxvKj1RGsDEYeQOwmDDpdqlZuiObZwH0Zv0ij1N1Dx4nNl/MRwXg7j1vYeHClfYfF0pAKhThLquxrJWkcPcZ0BJFNPuTm19MqdSGdv4L/mh1YG50ReIDL7QpEmfj6nDIwPf66c5tofxtAV9pTRW13xb157ON+TQfKdz5HULa7hKBg0hPtxFdYn0Pw+mJP4E6k6vlpNTfdEUS/l7xVbLev435tR3S/WYkqFzazquY+m4QGnXJlGEYKK5vUwtvcCTTmhpEgVU1YMIgaKlkQJ+cigvInkMhUYVwtwHRjVxAXK4f5S12LOM1zNidABq1lzXIQg0hCqqJ9XxDw0vEUjJGPvkeU4Er5jKi6odDR0t/QcmsxK+P6+FRHQoa2bs5HMxUcXZhOf0=
install: mvn -P !build-extras install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -P !build-extras test -B
before_install:
- openssl aes-256-cbc -K $encrypted_711e5bbf5b76_key -iv $encrypted_711e5bbf5b76_iv
  -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
- gpg --batch --fast-import .travis/codesigning.asc
deploy:
  skip_cleanup: true
  provider: script
  script: mvn -P sign,build-extras -s .travis/settings.xml deploy -DskipTests
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|develop)$"


