language: java
before_install:
  - pip install --user codecov
after_success:
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - dev@dattack.com
    on_success: always
    on_failure: always
