language: java
jdk:
- oraclejdk8
dist: trusty
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - dev@dattack.com
    on_success: always
    on_failure: always
env:
  global:
  - secure: aYMnYN6Up/PXG0ioSRkNNgSnQs4awvP5HEp3Qn0p3TWvfJyAbJKc2RRLPpEwWVGyC5zG9VYHG49gnuDwuF/P+KfTeRxIpPKk0tjtBKIDt6tkqTjuknYw6M2O6ZqWHg6GXfBL9wmlJ4pdqfs4bQ+oCJkGSNexA4r4NatBigd1OilnIEjNK2XsOSjIimigTxCg6vxZ2Q7v539YG+AKW82M8kxU1Wop6G4x6gboqjkkPvE7SVSUT3rfvWpsERV7XR7DJWiGuSca4CVAr0jisguFJ50QMBK9/tcJhSgrNVmUVlNX2sNXOsonzK3UAOY+57+m/iAJ7myPRUPCxkg1oMQsI25dpQM6lvYRH3wfHG5+PjL0Fc5dhu6RsDQZEWqcLIYjc6VBTaStOH9hMALAkDgYZry34m6S57a+enTW4FxctKZdkH0gk7v0uwGI6j2xu7wiUOs0YvzF45B5LkgF/HiL8moAveqkzdP86k9jaZ8X1tIN/LouSPbszW6k02SA0DPgPYlaopfmg4T/kWrV/iCmbBwmKdQNOv2EullfRWFoe/RXZVhjubLw6mHFjPbqjGE/u/OXDQc2fw+oQ6MOm6Bya4xthU61G+W90ay9qeQLH6crq7ekmPY8qZsUBxMoTH1TOW7wOfs8wdrVXAoDtmzc/QKAjCGvgunar+sikGpltSs=
  - secure: Unei9V4J5YPLAwQULDuEvZNdYkXk5FrlYsCYo+0rnFL7wyTvVqtfKWS9CgyHr3lo5dtyt7oHi6JcNboOnLsILjMm+s5M+5WtNxVNxvj5pb2vPN4RKhmXBg9zdhABfTQ0THFXv2V0BCkJnAv8FAcMk0ZjnLPyn3tYOiaD073JvWzCl5HZ9memBovd/4O9O48AHjp07HfhJIewC/3vbogeKBeJE40SBPvrpF1bTeYCWvHxXzNtzJmV9uBij26zZ67o8thaCPXtI3oRbV22ntF7SC4EsUL2qAnKFGlKlk05kjT2ToCQ4fZqf+Zvut3en2bwVgjN6HPHZGTZVxK8GLi6yMBYmD48BpGTuJKZVOheDDVfMN31qINrB5kdMn2s7JdO1xGDZiBGdg2G+eUJJRq8ji/c78EPTVX9akJH8w+a51FcZC2brYhqLRGDSqbnnMF94rQ6UyXrCpn5jLz+XUQNxwiWT4U268FhDeKiTHmFYUVAjXiwtFV6NIrhicVlpzNQFelZ+EzCDsaWZgRlftyLYb/x9YnB4PgY/Tn4Se6VCcT9aU+jWniz43k2IDiUBXR41USdWtd2P0rtb2osIOEBp957CxonHEku6RJofKyUI3Qs/ebCCQwq5R+t7J6z96TlPcXVdRZ4j7nfxg1yL+NpdULeamPmmD9FcpEi0s+y8B4=
  - secure: LwRonbQ4/C8fREdu9wgJ0YqFg+nX9ZFKAU+K2h1FuICEVJFEuUjOD2cMk6UMWWn8YdHmmQwJRzfpucgfZQIe0eAdtIwC4f93VAmj0VyJM1fyn6WRwoZ26kQusZhdmwDsY+oNK0a0gKW9g4SSpcNFckWErf/xP6z3rUkzIDH41WhAjQqUL3uUCaVIX3Yobuiy8uVKi/PRIHtdBIHow5wRfiQghOLFn7a9O2eIbaOONmejbg1JrXc8vJRdn07amOJB7bJRoVgFGUtcKaoC/HwlDGTw+4SuJ/nhxA+MYLlRlFwb53vbC4ITzhM8uF4V+psFLY417yPMdvp+2COu5pWyeDurap22KOuQyeWYf7iWcW88M7O35qMe5WHLTM4aVf5NTq1IiJYsrY/cW7w0h7+i3vZAdUKF6l0XLcgQL6tVgaQYTaBvyIVdAdy/2pGlpJePIHCJMJTDdvLNMsBB0kV3oWuYgANXRqcQX/P835ot6IzXSnO5ugaa/N3c5bVdlKSNgY7aF/+V7QBP7b5sKdNJD82Api8WTPAT8KRtut8FckQixiZXLRTNSg/Nx3nFS87+g8jSe9uZtxbAo0QQq/sYlh9eYA+6vyvxjh/K2GtRFt54AG8gda3JWAxOTD5QsT18eMZjiP7J2tFldMkU9rpeIjZsffvFLsFTY9I0cxRHj34=
  - secure: IwViuTr/jUli1PNUFPdvm8F92dKFjj07jdosDAjfebgyz4S9HTYwMz8oTwKaMFzeus7HZq9kggaGDw8bx8hFFKZsS6d9pwy/IdwntT9POiKllXCLKWp4M+K2aKy29khBv7rEHm7fjpjONOYIA1dq9Y3AdMxLAhaCdnq5UiLk4wK3+ZntiHok2C3C/BnCzary77yecJlGBysNLry4BlqRWuDA2CwQeFRgrNkVzi4NGdmpMaHZQ6RRVKpb/6EVjfphgI58A8ekBURJ4ZWV5S0hBG6W9V2wRruzQ7beKkEJCNQHeBvKsWN92jAQrkDDLLyUVCM5pYT9z4A7Gq9zD72NeuuQX9knfE8uXnhbxwhyOdZ1N6dX0FTgeyDRcrstem2AMtVso3GLWUZmiwAc0MC2hWqBb+NvsBLNy1w+tJYU245idmTvznGG9q15rj81YKttUgNDqwK23NCMm4k45BZnV1J3tp9/OQp4xCTD+MTxG0rronnSiByJKSv6ZqSyr5rh4sy200GqnmZDEAfJxX+DnWUezwC1GCE/Ckq9YONkXJuZPDQ7cOthPm1/ocn3PJuqXwqT8Y2B6no+ubcaaciavNGJ4IAIuWbNI4qn3HYrKHQdPT3R80GfTk+iBCulvpv3k3LN/VRDKRnT35LfgesZMF+FBAi4IKt78Q9Qac0kDIM=

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./.travis/before-deploy.sh
  - ./.travis/deploy.sh
